/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import Util.FILEIO;
import Util.IMAGE;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sean Zhang
 */
public class Launcher extends javax.swing.JFrame {

    /**
     * Creates new form launcher
     */
    public LoginEngine l;

    public Launcher() {
        initComponents();
        //makes the textfield transparent and white
        userTextField.setOpaque(false);
        fNameTxtField.setOpaque(false);
        lNameTxtField.setOpaque(false);
        uNameTxtField.setOpaque(false);
        passConfirmPField.setOpaque(false);
        passPField.setOpaque(false);
        imgURLTxtField.setOpaque(false);
        l = new LoginEngine();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new gfx.bg();
        loginPanel = new javax.swing.JPanel();
        signinUNamePanel = new javax.swing.JPanel();
        signInLabel = new javax.swing.JLabel();
        promptLabel = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        userLinePanel = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();
        underline = new javax.swing.JLabel();
        nextButton = new javax.swing.JLabel();
        createAcc = new javax.swing.JLabel();
        warnLabel = new javax.swing.JLabel();
        signUpPanel = new javax.swing.JPanel();
        signUpLabel = new javax.swing.JLabel();
        fNamePrompt = new javax.swing.JLabel();
        fNameTxtField = new javax.swing.JTextField();
        lNamePrompt = new javax.swing.JLabel();
        lNameTxtField = new javax.swing.JTextField();
        uNameTxtField = new javax.swing.JTextField();
        uNamePrompt = new javax.swing.JLabel();
        passPField = new javax.swing.JPasswordField();
        passConfirmPField = new javax.swing.JPasswordField();
        passPrompt = new javax.swing.JLabel();
        passConfirmPrompt = new javax.swing.JLabel();
        imgURLPrompt = new javax.swing.JLabel();
        imgURLTxtField = new javax.swing.JTextField();
        backButtonSignUp = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        nextButton2 = new javax.swing.JLabel();
        passcodePanel = new javax.swing.JPanel();
        userLinePanel1 = new javax.swing.JPanel();
        separator1 = new javax.swing.JSeparator();
        underline1 = new javax.swing.JLabel();
        promptLabel1 = new javax.swing.JLabel();
        signInLabel1 = new javax.swing.JLabel();
        nextButton1 = new javax.swing.JLabel();
        grayPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        uNameLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        exitLogin = new javax.swing.JLabel();
        passCodeField = new javax.swing.JPasswordField();
        userPanel = new javax.swing.JPanel();
        profileLabel1 = new javax.swing.JLabel();
        lNameLabel = new javax.swing.JLabel();
        fNameLabel1 = new javax.swing.JLabel();
        uNameLabelL = new javax.swing.JLabel();
        deleteUserButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgPanelMousePressed(evt);
            }
        });

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setPreferredSize(new java.awt.Dimension(350, 300));
        loginPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginPanelMousePressed(evt);
            }
        });
        loginPanel.setLayout(new java.awt.CardLayout());

        signinUNamePanel.setBackground(new java.awt.Color(255, 255, 255));

        signInLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        signInLabel.setText("Sign in");

        promptLabel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        promptLabel.setForeground(new java.awt.Color(61, 61, 61));
        promptLabel.setText("Username");
        promptLabel.setAlignmentX(0.5F);

        userTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userTextField.setBorder(null);
        userTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTextFieldFocusLost(evt);
            }
        });
        userTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userTextFieldKeyPressed(evt);
            }
        });

        userLinePanel.setBackground(new java.awt.Color(255, 51, 51));
        userLinePanel.setOpaque(false);
        userLinePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separator.setPreferredSize(new java.awt.Dimension(50, 8));
        userLinePanel.add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 1));

        underline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/img/in.gif"))); // NOI18N
        userLinePanel.add(underline, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 3));

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/img/nextButton.png"))); // NOI18N
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextButtonMouseReleased(evt);
            }
        });

        createAcc.setBackground(new java.awt.Color(0, 114, 255));
        createAcc.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        createAcc.setForeground(new java.awt.Color(0, 114, 255));
        createAcc.setText("Create an Account");
        createAcc.setPreferredSize(new java.awt.Dimension(97, 26));
        createAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createAccMousePressed(evt);
            }
        });

        warnLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout signinUNamePanelLayout = new javax.swing.GroupLayout(signinUNamePanel);
        signinUNamePanel.setLayout(signinUNamePanelLayout);
        signinUNamePanelLayout.setHorizontalGroup(
            signinUNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinUNamePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(signinUNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(signinUNamePanelLayout.createSequentialGroup()
                        .addComponent(createAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton))
                    .addComponent(userLinePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinUNamePanelLayout.createSequentialGroup()
                        .addGroup(signinUNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signInLabel)
                            .addComponent(promptLabel))
                        .addGap(220, 220, 220))
                    .addComponent(warnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        signinUNamePanelLayout.setVerticalGroup(
            signinUNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinUNamePanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(signInLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(promptLabel)
                .addGap(3, 3, 3)
                .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(userLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signinUNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextButton)
                    .addComponent(createAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        loginPanel.add(signinUNamePanel, "card2");

        signUpPanel.setBackground(new java.awt.Color(255, 255, 255));

        signUpLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        signUpLabel.setText("Sign up");

        fNamePrompt.setText("First Name");

        fNameTxtField.setBorder(null);

        lNamePrompt.setText("Last Name");

        lNameTxtField.setBorder(null);

        uNameTxtField.setBorder(null);
        uNameTxtField.setPreferredSize(new java.awt.Dimension(6, 20));

        uNamePrompt.setText("Username");

        passPField.setBorder(null);

        passConfirmPField.setBorder(null);

        passPrompt.setText("Password");

        passConfirmPrompt.setText("Confirm Password");

        imgURLPrompt.setText("Image URL (optional)");

        imgURLTxtField.setBorder(null);

        backButtonSignUp.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        backButtonSignUp.setForeground(new java.awt.Color(153, 153, 153));
        backButtonSignUp.setText("Go Back");
        backButtonSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonSignUpMouseClicked(evt);
            }
        });

        nextButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/img/nextButton.png"))); // NOI18N
        nextButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextButton2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(signUpPanelLayout.createSequentialGroup()
                            .addComponent(backButtonSignUp)
                            .addGap(184, 184, 184)
                            .addComponent(nextButton2))
                        .addGroup(signUpPanelLayout.createSequentialGroup()
                            .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator5)
                                .addComponent(passPrompt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(uNameTxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fNamePrompt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fNameTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(uNamePrompt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passPField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(imgURLPrompt)
                                .addComponent(lNamePrompt)
                                .addComponent(lNameTxtField)
                                .addComponent(passConfirmPrompt)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator4)
                                .addComponent(passConfirmPField)
                                .addComponent(jSeparator6)
                                .addComponent(imgURLTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(signUpLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(signUpLabel)
                .addGap(18, 18, 18)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fNamePrompt)
                            .addComponent(lNamePrompt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lNameTxtField)
                            .addComponent(fNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uNamePrompt)
                    .addComponent(imgURLPrompt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgURLTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(passConfirmPrompt))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passPrompt)))
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passConfirmPField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passPField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backButtonSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        loginPanel.add(signUpPanel, "card3");

        passcodePanel.setBackground(new java.awt.Color(255, 255, 255));

        userLinePanel1.setBackground(new java.awt.Color(255, 51, 51));
        userLinePanel1.setOpaque(false);
        userLinePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separator1.setPreferredSize(new java.awt.Dimension(50, 8));
        userLinePanel1.add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 1));

        underline1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/img/in.gif"))); // NOI18N
        userLinePanel1.add(underline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 3));

        promptLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        promptLabel1.setForeground(new java.awt.Color(61, 61, 61));
        promptLabel1.setText("Password");
        promptLabel1.setAlignmentX(0.5F);

        signInLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        signInLabel1.setText("Welcome");

        nextButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/img/nextButton.png"))); // NOI18N
        nextButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextButton1MouseReleased(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        nameLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        nameLabel.setAlignmentY(0.0F);

        uNameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        exitLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitLogin.setText("x");
        exitLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grayPanelLayout = new javax.swing.GroupLayout(grayPanel);
        grayPanel.setLayout(grayPanelLayout);
        grayPanelLayout.setHorizontalGroup(
            grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(uNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        grayPanelLayout.setVerticalGroup(
            grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grayPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(grayPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(uNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(exitLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        passCodeField.setBorder(null);
        passCodeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passCodeFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passCodeFieldFocusLost(evt);
            }
        });
        passCodeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passCodeFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout passcodePanelLayout = new javax.swing.GroupLayout(passcodePanel);
        passcodePanel.setLayout(passcodePanelLayout);
        passcodePanelLayout.setHorizontalGroup(
            passcodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passcodePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton1)
                .addGap(31, 31, 31))
            .addGroup(passcodePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(passcodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passcodePanelLayout.createSequentialGroup()
                        .addComponent(signInLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(passcodePanelLayout.createSequentialGroup()
                        .addGroup(passcodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userLinePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(promptLabel1)
                            .addComponent(grayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        passcodePanelLayout.setVerticalGroup(
            passcodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passcodePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(signInLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(promptLabel1)
                .addGap(5, 5, 5)
                .addComponent(passCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(userLinePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextButton1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        loginPanel.add(passcodePanel, "card4");

        lNameLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        lNameLabel.setText("Zhang");

        fNameLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        fNameLabel1.setText("Sean");

        uNameLabelL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uNameLabelL.setText("sean01zhang");

        deleteUserButton.setText("Delete");

        signOutButton.setText("Sign Out");
        signOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signOutButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(uNameLabelL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fNameLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(signOutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(fNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uNameLabelL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(signOutButton)
                            .addComponent(deleteUserButton)))
                    .addComponent(profileLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
        );

        loginPanel.add(userPanel, "card5");

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //this is the animation for the blue bar when the textfield is focused and unfocused
    ImageIcon in = new ImageIcon(getClass().getResource("/Res/img/in.gif"));
    ImageIcon out = new ImageIcon(getClass().getResource("/Res/img/out.gif"));

    /**
     * This is called when the focus of the text field is gained. Login stuff
     * turn blue
     *
     * @param evt the focus event
     */
    private void userTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTextFieldFocusGained
        in.getImage().flush();
        underline.setIcon(in);
        promptLabel.setForeground(new Color(0, 114, 255));
    }//GEN-LAST:event_userTextFieldFocusGained

    /**
     * This is called when focus of the text field is lost. It grays out the
     * login details
     *
     * @param evt the focus event
     */
    private void userTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTextFieldFocusLost
        out.getImage().flush();
        underline.setIcon(out);
        promptLabel.setForeground(new Color(61, 61, 61));
    }//GEN-LAST:event_userTextFieldFocusLost

    /**
     * This focuses on the login panel so that the user text field loses focus
     *
     * @param evt the mouse event
     */
    private void loginPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginPanelMousePressed
        this.requestFocusInWindow();
    }//GEN-LAST:event_loginPanelMousePressed

    /**
     * This focuses on the background panel so that the user text field loses
     * focus.
     *
     * @param evt
     */
    private void bgPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgPanelMousePressed
        this.requestFocusInWindow();
    }//GEN-LAST:event_bgPanelMousePressed

    //this is the animation icons for the next button
    ImageIcon nextButtonDep = (new ImageIcon(getClass().getResource("/Res/img/nextButtonDep.png")));
    ImageIcon nextButtonND = (new ImageIcon(getClass().getResource("/Res/img/nextButton.png")));

    /**
     * This method is called when the user wants to proceed in the login process
     *
     * @param evt the mouse event
     */
    private void nextButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMousePressed
        nextButton.setIcon(nextButtonDep);
        //do login stuff
        loginU(userTextField.getText());
    }//GEN-LAST:event_nextButtonMousePressed

    /**
     * This method is called to revert the icon to the undepressed state
     *
     * @param evt the mouse event
     */
    private void nextButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseReleased
        nextButton.setIcon(nextButtonND);
    }//GEN-LAST:event_nextButtonMouseReleased

    /**
     *
     * @param evt
     */
    private void userTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //do login stuff
            loginU(userTextField.getText());
        } else {
            warnLabel.setText("");
        }
    }//GEN-LAST:event_userTextFieldKeyPressed

    /**
     * Performs all the actions after entering in your username
     *
     * @param uName the username that was provided
     */
    public void loginU(String uName) {
        try {
            if (LoginEngine.isUser((uName)) != -1) {
                passcodePanel.setVisible(true);
                signinUNamePanel.setVisible(false);
                signUpPanel.setVisible(false);
                userPanel.setVisible(false);
                l.loadUser(uName);
                nameLabel.setText(((l.getUser().getfName())) + " " + ((l.getUser().getlName())));
                uNameLabel.setText(uName);
                warnLabel.setText("");
                profileLabel.setIcon(new ImageIcon(IMAGE.getResizedImage(IMAGE.getBufferedImageURL(((l.getUser().getProfileURL()))), profileLabel.getWidth(), profileLabel.getHeight())));
            } else {
                warnLabel.setText("This user does not exist");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This is called when the user wants to create a new account.
     *
     * @param evt mouse event
     */
    private void createAccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccMousePressed
        //switches panels to the signUp panel
        signinUNamePanel.setVisible(false);
        signUpPanel.setVisible(true);
        backButtonSignUp.setVisible(true);
    }//GEN-LAST:event_createAccMousePressed

    /**
     * This is called when the user wants to return to the main login screen
     *
     * @param evt mouse event
     */
    private void backButtonSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonSignUpMouseClicked
        signinUNamePanel.setVisible(true);
        signUpPanel.setVisible(false);
        userTextField.requestFocusInWindow();
        backButtonSignUp.setVisible(false);
        resetTxtFields();
        warnLabel.setText("");
    }//GEN-LAST:event_backButtonSignUpMouseClicked

    private void loginP() {
        if (LoginEngine.isPass(uNameLabel.getText(), new String(passCodeField.getPassword())) != -1) {
            userPanel.setVisible(true);
            passcodePanel.setVisible(false);
            signinUNamePanel.setVisible(false);
            signUpPanel.setVisible(false);

            try {
                fNameLabel1.setText((l.getUser().getfName()));
                lNameLabel.setText((l.getUser().getlName()));
                uNameLabelL.setText((l.getUser().getuName()));
                profileLabel1.setIcon(new ImageIcon(IMAGE.getResizedImage(IMAGE.getBufferedImageURL(((l.getUser().getProfileURL()))), profileLabel1.getWidth(), profileLabel1.getHeight())));
            } catch (Exception ex) {
            }
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect Password");
        }
    }

    private void nextButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButton1MousePressed
        nextButton1.setIcon(nextButtonDep);
    }//GEN-LAST:event_nextButton1MousePressed

    private void nextButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButton1MouseReleased
        nextButton1.setIcon(nextButtonND);
        //calls login method
        loginP();
    }//GEN-LAST:event_nextButton1MouseReleased

    private void exitLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLoginMouseClicked
        // TODO add your handling code here:
        signUpPanel.setVisible(false);
        signinUNamePanel.setVisible(true);
        passcodePanel.setVisible(false);
        passCodeField.setText("");
    }//GEN-LAST:event_exitLoginMouseClicked

    private void passCodeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passCodeFieldFocusGained
        in.getImage().flush();
        underline1.setIcon(in);
        promptLabel1.setForeground(new Color(0, 114, 255));
    }//GEN-LAST:event_passCodeFieldFocusGained

    private void passCodeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passCodeFieldFocusLost
        out.getImage().flush();
        underline1.setIcon(out);
        promptLabel1.setForeground(new Color(61, 61, 61));
    }//GEN-LAST:event_passCodeFieldFocusLost

    private void passCodeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passCodeFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginP();
        }
    }//GEN-LAST:event_passCodeFieldKeyPressed

    /**
     * Triggers a depressed icon of nextButton when pressed
     *
     * @param evt the mouse event
     */
    private void nextButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButton2MousePressed
        nextButton2.setIcon(nextButtonDep);
    }//GEN-LAST:event_nextButton2MousePressed

    /**
     * Signs up the user into the file
     *
     * @param evt the mouse event
     */
    private void nextButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButton2MouseReleased
        nextButton2.setIcon(nextButtonND);

        if (!badPass("dictbadpass.txt")) {
            try {
                //adds user to the file
                l.addUser((fNameTxtField.getText()), (lNameTxtField.getText()), (uNameTxtField.getText()), new String(passPField.getPassword()), (imgURLTxtField.getText()));
                //goes back to main screen
                signinUNamePanel.setVisible(true);
                signUpPanel.setVisible(false);
                userTextField.requestFocusInWindow();
                backButtonSignUp.setVisible(false);
                resetTxtFields();
                warnLabel.setText("");
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_nextButton2MouseReleased

    /**
     * Signs out the user.
     * @param evt the mouse event
     */
    private void signOutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutButtonMousePressed
        passcodePanel.setVisible(false);
        signinUNamePanel.setVisible(true);
        signUpPanel.setVisible(false);
        userPanel.setVisible(false);
        resetTxtFields();
    }//GEN-LAST:event_signOutButtonMousePressed

    /**
     * Checks if the password is bad
     *
     * @param fName the filename of the bad passwords
     * @return true if it is a bad password
     */
    public Boolean badPass(String fName) {
        //if all fields are empty
        if (passPField.getPassword().length == 0 || passConfirmPField.getPassword().length == 0 || fNameTxtField.getText().isEmpty() || lNameTxtField.getText().isEmpty() || uNameTxtField.getText().isEmpty()) {
            //prompt user to fill all fields
            JOptionPane.showMessageDialog(this, "Please fill in all mandatory fields.");

            //clear password field
            passPField.setText("");
            passConfirmPField.setText("");
            return true;
        }

        String s1 = new String(passPField.getPassword());
        String s2 = new String(passConfirmPField.getPassword());

        if (!s1.equals(s2)) {
            //prompt user that passwords do not match
            JOptionPane.showMessageDialog(this, "Passwords do not match. Try Again.");
            //clear password field
            passPField.setText("");
            passConfirmPField.setText("");
            return true;
        }

        //creates a new instance of file with the given path of the file.
        File f = new File("src/Res/" + fName);
        //creates a scanner variable
        Scanner input;

        //catches exceptions related to FileNotFoundException
        try {
            //creates a new instance of Scanner in the input variable
            input = new Scanner(f);

            //adds every line of the file into the output string.
            while (input.hasNext()) {
                if (s1.equals(input.nextLine())) {
                    JOptionPane.showMessageDialog(this, "This Password is too common. Try Again.");
                    passPField.setText("");
                    passConfirmPField.setText("");
                    return true;
                }
            }

            //closes the scanner
            input.close();
        } catch (FileNotFoundException ex) {
        }

        //if duplicate user
        try {
            if (LoginEngine.isUser(uNameTxtField.getText()) != -1) {
                //prompt user that there is already a user existing with that username
                JOptionPane.showMessageDialog(this, "A user already exists with this username. Try Again.");
                passPField.setText("");
                passConfirmPField.setText("");
                uNameTxtField.setText("");
                return true;
            }
        } catch (Exception ex) {
        }

        return false;

    }

    public void resetTxtFields() {
        userTextField.setText("");
        fNameTxtField.setText("");
        lNameTxtField.setText("");
        uNameTxtField.setText("");
        passConfirmPField.setText("");
        passPField.setText("");
        imgURLTxtField.setText("");
        fNameLabel1.setText("");
        lNameLabel.setText("");
        uNameLabelL.setText("");
        nameLabel.setText("");
        uNameLabel.setText("");
        passCodeField.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Launcher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButtonSignUp;
    private gfx.bg bgPanel;
    private javax.swing.JLabel createAcc;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel exitLogin;
    private javax.swing.JLabel fNameLabel1;
    private javax.swing.JLabel fNamePrompt;
    private javax.swing.JTextField fNameTxtField;
    private javax.swing.JPanel grayPanel;
    private javax.swing.JLabel imgURLPrompt;
    private javax.swing.JTextField imgURLTxtField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JLabel lNamePrompt;
    private javax.swing.JTextField lNameTxtField;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nextButton;
    private javax.swing.JLabel nextButton1;
    private javax.swing.JLabel nextButton2;
    private javax.swing.JPasswordField passCodeField;
    private javax.swing.JPasswordField passConfirmPField;
    private javax.swing.JLabel passConfirmPrompt;
    private javax.swing.JPasswordField passPField;
    private javax.swing.JLabel passPrompt;
    private javax.swing.JPanel passcodePanel;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JLabel profileLabel1;
    private javax.swing.JLabel promptLabel;
    private javax.swing.JLabel promptLabel1;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator1;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JLabel signInLabel1;
    private javax.swing.JButton signOutButton;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JPanel signinUNamePanel;
    private javax.swing.JLabel uNameLabel;
    private javax.swing.JLabel uNameLabelL;
    private javax.swing.JLabel uNamePrompt;
    private javax.swing.JTextField uNameTxtField;
    private javax.swing.JLabel underline;
    private javax.swing.JLabel underline1;
    private javax.swing.JPanel userLinePanel;
    private javax.swing.JPanel userLinePanel1;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTextField userTextField;
    private javax.swing.JLabel warnLabel;
    // End of variables declaration//GEN-END:variables
}
